version: '3.5'

services:
  spark-master:
    image: osekoo/spark:3.5.0
    container_name: spark-master
    build:
      context: ./
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
    ports:
      - '${SPARK_MASTER_PORT:-7077}:${SPARK_MASTER_PORT:-7077}'
      - '${SPARK_WEBUI_PORT:-8080}:${SPARK_WEBUI_PORT:-8080}'

  spark-worker:
    image: osekoo/spark:3.5.0
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
    deploy:
      replicas: 1
    depends_on:
      - spark-master

  spark-submit:
    image: osekoo/spark:3.5.0
    container_name: spark-submit
    env_file:
      - .env
    environment:
      - SPARK_MODE=submit
    ports:
      - '${SPARK_APP_PORT:-4040}:${SPARK_APP_PORT:-4040}'
    volumes:
      - "./:/app"
    depends_on:
      - spark-worker
